# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='webmapingapp',
            name='preview',
            field=models.FilePathField(allow_folders=True, blank=True, path='/app/defocus/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='webmapingapp',
            name='configuration',
            field=models.TextField(blank=True, verbose_name='configuration'),
        ),
    ]
