# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:36
from __future__ import unicode_literals

import arcgis_marketplace.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_marketplace', '0002_auto_20170526_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmapingapp',
            name='preview',
            field=arcgis_marketplace.fields.SymlinkField(blank=True, source='file', verbose_name='preview'),
        ),
    ]
